### ISSUE TITLE
Make it a monorepo and add a release management library

### ISSUE THREAD

**Issue by MESSELMIyahya** [HassanDev13/stepper-react#2]
Make it a monorepo and add a release management library like [Changesets](https://changesets-docs.vercel.app/)

**Comment by HassanDev13** [comment]
I know what monorepo means, but i don't know why you are using it in this context 🤔

**Comment by MESSELMIyahya** [comment]
I see that your library will look so good if separate the component from the website, and this also will help you when you start versioning and publishing to NPM, Good luck

**Comment by HassanDev13** [comment]
I’ll keep that in mind as I continue to develop the project. Appreciate the support!
